name: Deploy home app

on:
  workflow_dispatch:

jobs:
  deploy-home-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy shared UI
        run: |
          cp -r shared-ui home-app/src

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14.16.0"

      - name: Install dependencies
        run: |
          cd home-app
          npm install

      - name: Build production app
        run: |
          cd home-app
          npm run build
          mkdir -p dist/home-app
          mv dist/*.* dist/home-app

      - name: Remove existing S3 bucket folder
        uses: vitorsgomes/s3-rm-action@v1.0.1
        with:
          args: --recursive
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PATH_TO_DELETE: home-app

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: home-app/dist
