name: Deploy navbar app

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      AWS_PRODUCTION_BUCKET_NAME:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  deploy-navbar-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14.16.0"

      - name: Setup file structure for shared UI
        run: |
          cp -r shared-ui navbar-app/src

      - name: Install dependencies
        run: |
          cd navbar-app
          npm install

      - name: Build production app
        run: |
          cd navbar-app
          npm run build
          mkdir -p dist/navbar-app
          mv dist/*.* dist/navbar-app

      - name: Remove existing S3 bucket folder
        uses: vitorsgomes/s3-rm-action@v1.0.1
        with:
          args: --recursive
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PATH_TO_DELETE: navbar-app

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: navbar-app/dist
