name: Micro Frontend Deployments

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy-root:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd mfe-root
          npm install

      - name: Build production app
        run: |
          cd mfe-root
          npm run build
          mkdir -p dist/mfe-root
          mv dist/*.* dist/mfe-root

      - name: Deploy to S3
        # NEXT make this @0.5.1 once it works,
        # so that we aren't just using latest version without verification
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "mfe-root/dist"

  build-and-deploy-home-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install dependencies
        run: |
          cd home-app
          npm install
      - name: Build production app
        run: |
          cd home-app
          npm run build
          mkdir -p dist/home-app
          mv dist/*.* dist/home-app
      - name: Deploy to S3
        # NEXT make this @0.5.1 once it works,
        # so that we aren't just using latest version without verification
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "home-app/dist"

  build-and-deploy-about-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install dependencies
        run: |
          cd about-app
          npm install
      - name: Build production app
        run: |
          cd about-app
          npm run build
          mkdir -p dist/about-app
          mv dist/*.* dist/about-app
      - name: Deploy to S3
        # NEXT make this @0.5.1 once it works,
        # so that we aren't just using latest version without verification
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "about-app/dist"

  build-and-deploy-contact-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install dependencies
        run: |
          cd contact-app
          npm install
      - name: Build production app
        run: |
          cd contact-app
          npm run build
          mkdir -p dist/contact-app
          mv dist/*.* dist/contact-app
      - name: Deploy to S3
        # NEXT make this @0.5.1 once it works,
        # so that we aren't just using latest version without verification
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "contact-app/dist"

  build-and-deploy-navbar-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install dependencies
        run: |
          cd navbar-app
          npm install
      - name: Build production app
        run: |
          cd navbar-app
          npm run build
          mkdir -p dist/navbar-app
          mv dist/*.* dist/navbar-app
      - name: Deploy to S3
        # NEXT make this @0.5.1 once it works,
        # so that we aren't just using latest version without verification
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "navbar-app/dist"
# LEFTOFF lets just create a job for each m-app, and then any change to any will of course build and upload everything.
# so once i have achieved above, then make it so that the CI checks for changes within each m-app, and only builds + uploads when there is a specific job selected or triggered, similiar to our GITLAB pipelines
